--------------------------------------------------------
--  File created - Friday-August-14-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."ACCOUNTS" 
   (	"ACCT_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"INIT_BAL" NUMBER(20,4), 
	"BIRTHDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."TRANSACTIONS" 
   (	"TRAN_ID" NUMBER(*,0), 
	"ACCT_ID" NUMBER(*,0), 
	"AMOUNT" NUMBER(20,4), 
	"TRAN_DATE" DATE, 
	"TRAN_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.ACCOUNTS
SET DEFINE OFF;
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (555,'lkdfg',1675,null);
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (5632,'alcie',5000,to_date('06-MAY-00','DD-MON-RR'));
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (5524,'tina',122.9,to_date('06-MAY-14','DD-MON-RR'));
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (3213,'Wally',6799.56,to_date('03-JUN-99','DD-MON-RR'));
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (4213,'Roofus',3420,to_date('10-JUL-07','DD-MON-RR'));
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE) values (4221,'Gallant',-221,to_date('11-JUL-07','DD-MON-RR'));
REM INSERTING into TESTDB.TRANSACTIONS
SET DEFINE OFF;
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (17,5524,-30.05,to_date('04-MAY-14','DD-MON-RR'),'d');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (18,3213,-500.44,to_date('04-MAY-14','DD-MON-RR'),'c');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (19,555,20,to_date('06-MAY-14','DD-MON-RR'),'dep');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (12,5524,-20,to_date('02-FEB-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (13,5524,500,to_date('02-MAR-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (14,5524,-60,to_date('02-MAR-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (15,5524,-2,to_date('05-APR-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (7,555,-30,to_date('02-FEB-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (8,555,2000,to_date('02-FEB-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (9,555,-500,to_date('07-AUG-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (10,555,200,to_date('02-MAY-14','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (11,4221,-10,to_date('02-MAY-14','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (3,4213,-50,to_date('04-MAY-14','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (6,4221,-500,to_date('01-AUG-11','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (16,5524,-200,to_date('02-MAY-13','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (2,555,200,to_date('07-JUL-14','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (4,4213,-200,to_date('04-MAY-14','DD-MON-RR'),null);
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (5,4221,5000,to_date('04-FEB-13','DD-MON-RR'),null);
--------------------------------------------------------
--  DDL for Index SYS_C007305
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."SYS_C007305" ON "TESTDB"."ACCOUNTS" ("ACCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007306
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."SYS_C007306" ON "TESTDB"."TRANSACTIONS" ("TRAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."ACCOUNTS" ADD PRIMARY KEY ("ACCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."TRANSACTIONS" ADD PRIMARY KEY ("TRAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
